name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VRESION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  mior:
    labels:
      - 'mior'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels:
  - 'exclude from changelog'
template: |
  ## Changes

  $CHANGES